FROM docker.io/supabase/edge-runtime:v1.74.2@sha256:a82676277615aee03c4f288cbbbf68dedb5ba8693073e567ab8dbfdd11ba5d45

COPY docker/NOTICE docker/LICENSE.supabase /usr/share/licenses/pomodoist/

COPY docker/functions/main /home/deno/functions/main
COPY supabase/functions /home/deno/functions
