FROM public.ecr.aws/supabase/edge-runtime:v1.74.2

COPY docker/NOTICE docker/LICENSE.supabase /usr/share/licenses/pomodoist/

COPY docker/functions/main /home/deno/functions/main
COPY supabase/functions /home/deno/functions
